import api from './api.js'

export const listSnippets = (params) => api.get('/snippets', { params })
export const searchSnippets = (params) => api.get('/snippets/search', { params })
export const popularTags = () => api.get('/snippets/popular-tags')
export const createSnippet = (snippet) => api.post('/snippets', snippet)
export const getSnippet = (id) => api.get(`/snippets/${id}`)
export const getSnippetVersions = (id) => api.get(`/snippets/${id}/versions`)
export const getSnippetVersion = (id, version) => api.get(`/snippets/${id}/versions/${version}`)
export const updateSnippet = (id, snippet) => api.put(`/snippets/${id}`, snippet)
export const setVisibility = (id, visibility) => api.patch(`/snippets/${id}/visibility`, { visibility })
export const getPublicSnippet = (slug) => api.get(`/public/snippets/${encodeURIComponent(slug)}`)
export const deleteSnippet = (id) => api.delete(`/snippets/${id}`)
export const restoreSnippet = (id) => api.post(`/snippets/${id}/restore`)
export const favoriteSnippet = (id) => api.post(`/snippets/${id}/favorite`)
export const unfavoriteSnippet = (id) => api.delete(`/snippets/${id}/favorite`)