import { useEffect, useState } from 'react'
import * as collectionService from '../services/collectionService.js'
import * as snippetService from '../services/snippetService.js'

export default function Collections() {
  const [collections, setCollections] = useState([]); const [snippets, setSnippets] = useState([]); const [form, setForm] = useState({ name: '', description: '' }); const [editing, setEditing] = useState(null); const [error, setError] = useState('')
  async function load() { try { const [{ data: collectionData }, { data: snippetData }] = await Promise.all([collectionService.listCollections(), snippetService.listSnippets({ sort: 'alphabetical' })]); setCollections(collectionData.data.collections); setSnippets(snippetData.data.snippets) } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load collections.') } }
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer) }, [])
  async function save(event) { event.preventDefault(); try { if (editing) await collectionService.updateCollection(editing._id, form); else await collectionService.createCollection(form); setForm({ name: '', description: '' }); setEditing(null); await load() } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save collection.') } }
  async function remove(collection) { try { await collectionService.deleteCollection(collection._id); await load() } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to delete collection.') } }
  async function changeSnippet(collection, snippetId, included) { try { await (included ? collectionService.removeSnippet(collection._id, snippetId) : collectionService.addSnippet(collection._id, snippetId)); await load() } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to update collection.') } }
  return <main className="page-shell"><div className="page-heading"><div><p className="eyebrow">CODEVAULT / COLLECTIONS</p><h1>Collections</h1><p>Group snippets into focused working sets.</p></div></div>{error && <p className="error">{error}</p>}<form className="collection-form" onSubmit={save}><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Collection name" required /><input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Description" /><button className="primary-button">{editing ? 'Save collection' : 'Create collection'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm({ name: '', description: '' }) }}>Cancel</button>}</form><div className="collection-grid">{collections.map((collection) => <article className="collection-card" key={collection._id}><div className="collection-card-header"><div><h2>{collection.name}</h2><p>{collection.description || 'No description yet.'}</p></div><strong>{collection.snippets?.length || 0}</strong></div><div className="collection-snippets">{snippets.map((snippet) => { const included = collection.snippets?.some((item) => (item._id || item) === snippet._id); return <label key={snippet._id}><input type="checkbox" checked={included} onChange={() => changeSnippet(collection, snippet._id, included)} />{snippet.title}</label> })}</div><div className="card-actions"><button type="button" onClick={() => { setEditing(collection); setForm({ name: collection.name, description: collection.description || '' }) }}>Rename</button><button type="button" className="danger-text" onClick={() => remove(collection)}>Delete</button></div></article>)}</div></main>
}