import { Check, Copy, Download, Heart, Share2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'

import ConfirmDialog from '../components/ConfirmDialog.jsx'
import * as snippetService from '../services/snippetService.js'
import CodeEditor from '../components/CodeEditor.jsx'
import { downloadCode } from '../utils/codeUtils.js'
import { useToast } from '../hooks/useToast.js'

export default function SnippetDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const { showToast } = useToast(); const [snippet, setSnippet] = useState(null); const [error, setError] = useState(''); const [confirming, setConfirming] = useState(false); const [fullscreen, setFullscreen] = useState(false); const [shareOpen, setShareOpen] = useState(false); const [copied, setCopied] = useState(false)
  useEffect(() => { snippetService.getSnippet(id).then(({ data }) => setSnippet(data.data.snippet)).catch((requestError) => setError(requestError.response?.data?.message || 'Snippet not found.')) }, [id])
  async function remove() { try { await snippetService.deleteSnippet(id); navigate('/snippets') } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to delete snippet.') } }
  async function toggleFavorite() { try { const { data } = await (snippet.favorites > 0 ? snippetService.unfavoriteSnippet(id) : snippetService.favoriteSnippet(id)); setSnippet(data.data.snippet) } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to update favorite.') } }
  async function toggleVisibility() { try { const { data } = await snippetService.setVisibility(id, snippet.visibility === 'public' ? 'private' : 'public'); setSnippet(data.data.snippet); setShareOpen(data.data.snippet.visibility === 'public') } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to update visibility.') } }
  async function copyShareLink() { await navigator.clipboard.writeText(`${window.location.origin}/s/${snippet.slug}`); setCopied(true); showToast('Public link copied.'); window.setTimeout(() => setCopied(false), 1800) }
  if (error) return <main className="page-shell"><p className="error">{error}</p><Link to="/snippets">Back to snippets</Link></main>
  if (!snippet) return <main className="page-shell"><p className="status">Loading snippet...</p></main>
  const isFavorite = snippet.favorites > 0
  const shareUrl = `${window.location.origin}/s/${snippet.slug}`
  return <main className="page-shell"><div className="page-heading"><div><p className="eyebrow">{snippet.language} / {snippet.visibility}</p><h1>{snippet.title}</h1><p>{snippet.description}</p></div><div className="card-actions"><button type="button" className={`favorite-button ${isFavorite ? 'is-favorite' : ''}`} onClick={toggleFavorite}><Heart size={17} fill={isFavorite ? 'currentColor' : 'none'} /> {isFavorite ? 'Unfavorite' : 'Favorite'}</button><button type="button" onClick={() => setShareOpen((current) => !current)}><Share2 size={16} /> Share</button><Link to={`/snippets/${id}/edit`}>Edit</Link><Link to={`/snippets/${id}/versions`}>Version history</Link><button type="button" className="danger-text" onClick={() => setConfirming(true)}>Delete</button></div></div>{shareOpen && <section className="share-panel"><strong>{snippet.visibility === 'public' ? 'Public link' : 'This snippet is private'}</strong>{snippet.visibility === 'public' && <div className="share-link"><input readOnly value={shareUrl} aria-label="Public snippet link" /><button type="button" onClick={copyShareLink}>{copied ? <Check size={16} /> : <Copy size={16} />} {copied ? 'Copied' : 'Copy link'}</button></div>}<button type="button" onClick={toggleVisibility}>{snippet.visibility === 'public' ? 'Make private' : 'Publish snippet'}</button></section>}<div className="detail-meta"><span>Updated {new Date(snippet.updatedAt).toLocaleString()}</span><span>{snippet.views} views</span><span>{snippet.favorites} favorites</span></div><div className="detail-code"><div className="detail-code-actions"><button type="button" onClick={() => downloadCode(snippet.title, snippet.language, snippet.code)}><Download size={16} /> Download</button></div><CodeEditor value={snippet.code} language={snippet.language} readOnly fullscreen={fullscreen} onToggleFullscreen={() => setFullscreen((current) => !current)} /></div><div className="tag-list">{snippet.tags?.map((tag) => <span key={tag}>#{tag}</span>)}</div><ConfirmDialog open={confirming} title="Delete this snippet?" message="It will move to Trash and can be restored later." onCancel={() => setConfirming(false)} onConfirm={remove} /></main>
}
